In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
import numpy as np

In [2]:
tokenizer=Tokenizer()
data=" I Love"
corpus= data.lower().split("\n")
tokenizer.fit_on_texts(corpus)
total_words=len(tokenizer.word_index)+1
print(tokenizer.word_index)
print(total_words)

{'i': 1, 'love': 2}
3


In [3]:
sentences=['I love This world',
           'World is so beautiful!'
          ]
tokenizer.fit_on_texts(sentences)
word_index =tokenizer.word_index

In [4]:
print(word_index)

{'i': 1, 'love': 2, 'world': 3, 'this': 4, 'is': 5, 'so': 6, 'beautiful': 7}


In [5]:
sequences= tokenizer.texts_to_sequences(sentences)

In [6]:
print(sequences)

[[1, 2, 4, 3], [3, 5, 6, 7]]


In [26]:
sentences1=['I  really love my dog',
           'my dog loves my manatee'
          ]

In [27]:
tokenizer.fit_on_texts(sentences1)
word_index =tokenizer.word_index

In [28]:
print(word_index)

{'my': 1, 'dog': 2, 'i': 3, 'love': 4, 'really': 5, 'loves': 6, 'manatee': 7, 'world': 8, 'this': 9, 'is': 10, 'so': 11, 'beautiful': 12}


In [29]:
sequences1= tokenizer.texts_to_sequences(sentences1)

In [30]:
print (sequences1)

[[3, 5, 4, 1, 2], [1, 2, 6, 1, 7]]


In [34]:
from tensorflow.keras.preprocessing.text import Tokenizer

train_data=['I  love my dog',
           'I love my cat',
            'You love my dog!',
            'Do you think my dog is amazing?'
            
          ]
tokenizer=Tokenizer(num_words=100)
tokenizer.fit_on_texts(train_data)
word_index =tokenizer.word_index
T1=tokenizer.texts_to_sequences(train_data)
print(word_index)
print(T1)

{'my': 1, 'love': 2, 'dog': 3, 'i': 4, 'you': 5, 'cat': 6, 'do': 7, 'think': 8, 'is': 9, 'amazing': 10}
[[4, 2, 1, 3], [4, 2, 1, 6], [5, 2, 1, 3], [7, 5, 8, 1, 3, 9, 10]]


In [35]:
test_data=['I  really love my dog',
           'my dog loves my manatee'
          ]
T2=tokenizer.texts_to_sequences(test_data)
print(word_index)
print(T2)

{'my': 1, 'love': 2, 'dog': 3, 'i': 4, 'you': 5, 'cat': 6, 'do': 7, 'think': 8, 'is': 9, 'amazing': 10}
[[4, 2, 1, 3], [1, 3, 1]]


In [36]:
from tensorflow.keras.preprocessing.text import Tokenizer

train_data=['I  love my dog',
           'I love my cat',
            'You love my dog!',
            'Do you think my dog is amazing?'
            
          ]
tokenizer=Tokenizer(num_words=100,oov_token="<00v>")
tokenizer.fit_on_texts(train_data)
word_index =tokenizer.word_index
T1=tokenizer.texts_to_sequences(train_data)
print(word_index)
print(T1)

{'<00v>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]


In [37]:
test_data=['I  really love my dog',
           'my dog loves my manatee'
          ]
T2=tokenizer.texts_to_sequences(test_data)
print(word_index)
print(T2)

{'<00v>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]


In [39]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

train_data=['I  love my dog',
           'I love my cat',
            'You love my dog!',
            'Do you think my dog is amazing?'
            
          ]
tokenizer=Tokenizer(num_words=100,oov_token="<00v>")
tokenizer.fit_on_texts(train_data)
word_index =tokenizer.word_index
Seq=tokenizer.texts_to_sequences(train_data)
padded=pad_sequences(Seq)
print(word_index)
print(Seq)
print(padded)

{'<00v>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]
[[ 0  0  0  5  3  2  4]
 [ 0  0  0  5  3  2  7]
 [ 0  0  0  6  3  2  4]
 [ 8  6  9  2  4 10 11]]


In [40]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

train_data=['I  love my dog',
           'I love my cat',
            'You love my dog!',
            'Do you think my dog is amazing?'
            
          ]
tokenizer=Tokenizer(num_words=100,oov_token="<00v>")
tokenizer.fit_on_texts(train_data)
word_index =tokenizer.word_index
Seq=tokenizer.texts_to_sequences(train_data)
padded=pad_sequences(Seq, padding='post')
print(word_index)
print(Seq)
print(padded)

{'<00v>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]
[[ 5  3  2  4  0  0  0]
 [ 5  3  2  7  0  0  0]
 [ 6  3  2  4  0  0  0]
 [ 8  6  9  2  4 10 11]]


In [42]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

train_data=['I  love my dog',
           'I love my cat',
            'You love my dog!',
            'Do you think my dog is amazing?'
            
          ]
tokenizer=Tokenizer(num_words=100,oov_token="<00v>")
tokenizer.fit_on_texts(train_data)
word_index =tokenizer.word_index
Seq=tokenizer.texts_to_sequences(train_data)
padded=pad_sequences(Seq,  maxlen=5)
print(word_index)
print(Seq)
print(padded)

{'<00v>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]
[[ 0  5  3  2  4]
 [ 0  5  3  2  7]
 [ 0  6  3  2  4]
 [ 9  2  4 10 11]]


In [ ]:
-----------Training and Testing-------------------------------

In [99]:
import json
import requests


datastore = requests.get('https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json')
print(datastore.text[0:450])
sentences = []
labels = []
urls = []

for item in datastore.json():
    sentences.append(item['headline'])
    labels.append(item['is_sarcastic'])
    urls.append(item['article_link'])

tokenizer=Tokenizer(oov_token="<00v>")
tokenizer.fit_on_texts(sentences)
word_index =tokenizer.word_index
#print(word_index)
Seq=tokenizer.texts_to_sequences(sentences)
padded=pad_sequences(Seq , padding='post')
print(Seq[0])
print(padded[0])
print(padded.shape)

[
{"article_link": "https://www.huffingtonpost.com/entry/versace-black-code_us_5861fbefe4b0de3a08f600d5", "headline": "former versace store clerk sues over secret 'black code' for minority shoppers", "is_sarcastic": 0},
{"article_link": "https://www.huffingtonpost.com/entry/roseanne-revival-review_us_5ab3a497e4b054d118e04365", "headline": "the 'roseanne' revival catches up to our thorny political mood, for better and worse", "is_sarcastic": 0},
[308, 15115, 679, 3337, 2298, 48, 382, 2576, 15116, 6, 2577, 8434]
[  308 15115   679  3337  2298    48   382  2576 15116     6  2577  8434
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0]
(26709, 40)


In [100]:
training_size = round(len(sentences) * .75)
print(training_size)
print(len(sentences))

20032
26709


In [101]:
training_sentences = sentences[0:training_size]
testing_sentences = sentences[training_size:]
training_labels = labels[0:training_size]
testing_labels = labels[training_size:]

In [102]:
tokenizer = Tokenizer(10000,oov_token='oov_tok')
tokenizer.fit_on_texts(training_sentences)

In [103]:
training_sequences = tokenizer.texts_to_sequences(training_sentences)
training_padded = pad_sequences(training_sequences, maxlen= 100, padding='post', truncating='post')
testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences, maxlen= 100, padding='post', truncating='post')

In [9]:
embedding_dim = 16
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(10000, embedding_dim, input_length=100),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 100, 16)           160000    
_________________________________________________________________
global_average_pooling1d_1 ( (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 24)                408       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 25        
Total params: 160,433
Trainable params: 160,433
Non-trainable params: 0
_________________________________________________________________


In [105]:
training_padded = np.array(training_padded)
training_labels = np.array(training_labels)
testing_padded = np.array(testing_padded)
testing_labels = np.array(testing_labels)
# Training the model
num_epochs = 30
history = model.fit(training_padded, training_labels, epochs=num_epochs, validation_data=(testing_padded, testing_labels), verbose=2)

Train on 20032 samples, validate on 6677 samples
Epoch 1/30
20032/20032 - 4s - loss: 0.6578 - acc: 0.6027 - val_loss: 0.5407 - val_acc: 0.8016
Epoch 2/30
20032/20032 - 4s - loss: 0.3935 - acc: 0.8435 - val_loss: 0.3706 - val_acc: 0.8426
Epoch 3/30
20032/20032 - 4s - loss: 0.2876 - acc: 0.8848 - val_loss: 0.3450 - val_acc: 0.8564
Epoch 4/30
20032/20032 - 4s - loss: 0.2389 - acc: 0.9052 - val_loss: 0.3433 - val_acc: 0.8558
Epoch 5/30
20032/20032 - 3s - loss: 0.2049 - acc: 0.9213 - val_loss: 0.3655 - val_acc: 0.8436
Epoch 6/30
20032/20032 - 4s - loss: 0.1797 - acc: 0.9308 - val_loss: 0.3632 - val_acc: 0.8544
Epoch 7/30
20032/20032 - 3s - loss: 0.1578 - acc: 0.9414 - val_loss: 0.3942 - val_acc: 0.8453
Epoch 8/30
20032/20032 - 4s - loss: 0.1407 - acc: 0.9496 - val_loss: 0.4045 - val_acc: 0.8510
Epoch 9/30
20032/20032 - 3s - loss: 0.1263 - acc: 0.9539 - val_loss: 0.4221 - val_acc: 0.8504
Epoch 10/30
20032/20032 - 3s - loss: 0.1131 - acc: 0.9608 - val_loss: 0.4588 - val_acc: 0.8438
Epoch 11/3

In [113]:
sentence=[ "Please try to schedule meetings around my job interviews.", 
          "I send pointless emails late at night to impress coworkers."]
sequences = tokenizer.texts_to_sequences(sentence)
padded = pad_sequences(sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
print(model.predict(padded))

[[0.9997178 ]
 [0.16032079]]
